services:
  flask:
    image: image-flask-docker-compose
    build: .
    container_name: container-flask-docker-compose
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1